version: "3.8"

services:
  db_notify:
    image: postgres:latest
    container_name: webhook_notify_postgres_db
    env_file: .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - webhook_notify_postgres_data:/var/lib/postgres/data
    networks:
      - webhook_notify_network

  webhook_notify:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: webhook_notify
    command: >
      sh -c "./wait-for-it.sh db_notify:${DB_PORT} -- python manage.py makemigrations &&
            python manage.py migrate &&
            python manage.py collectstatic --noinput &&
            gunicorn config.wsgi:application --bind 0.0.0.0:8000"
    ports:
      - "8061:8000"
    volumes:
      - static_volume:/webhook_notify/staticfiles
    env_file: 
      - ./config/.env
    depends_on:
      - db_notify
    networks:
      - webhook_notify_network

networks:
  webhook_notify_network:
    driver: bridge

volumes:
  webhook_notify_postgres_data:
  static_volume: